import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
// import Sidebar from "@/components/Sidebar"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Outlet Ops',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
      <body className={`${inter.className}`}>
        {children}
      </body>
    </html>
  )
}
